@estagio_webapi_HostAddress = http://localhost:56192

POST {{estagio_webapi_HostAddress}}/orientadores
Content-Type: application/json

{
    "nome":"Roberto Carlos",
    "email":"essecarasoueu@email.com",
    "telefone":"(27)98888-8888"
}

###

GET {{estagio_webapi_HostAddress}}/orientadores

###

GET {{estagio_webapi_HostAddress}}/orientadores/21
Content-Type: application/json

###

PUT {{estagio_webapi_HostAddress}}/orientadores/21
Content-Type: application/json

{
    "id": 21,
    "nome":"Roberto Carlos",
    "email":"tantasemocoes@email.com",
    "telefone":"(27)98888-8888"
}

###

DELETE {{estagio_webapi_HostAddress}}/orientadores/21

###

POST {{estagio_webapi_HostAddress}}/alunos
Content-Type: application/json

{
  "nome":"Char",
  "matricula":"20221bsi0344"
}

###

GET {{estagio_webapi_HostAddress}}/alunos/1
Content-Type: application/json

###

PUT {{estagio_webapi_HostAddress}}/alunos/1
Content-type: application/json

{
  "nome": "Thiago",
  "matricula": "20221bsi0344"
}

###

DELETE {{estagio_webapi_HostAddress}}/alunos/1

###

POST {{estagio_webapi_HostAddress}}/empresas/
Content-Type: application/json

{
  "nome":"IFES"
}

###
PUT {{estagio_webapi_HostAddress}}/empresas/1
Content-Type: application/json

{
  "nome":"REC"
}

###

GET {{estagio_webapi_HostAddress}}/empresas/

###

DELETE {{estagio_webapi_HostAddress}}/empresas/1

###

POST {{estagio_webapi_HostAddress}}/estagios/
Content-Type: application/json

{
  "alunoId": 1,
  "orientadorId": 1,
  "situacao":1,
  "empresaId": 1,
  "dataInicio": "2021-09-01",
  "dataFim": "2022-09-01",
  "status": 1
}

###

GET {{estagio_webapi_HostAddress}}/estagios/

###
GET {{estagio_webapi_HostAddress}}/estagios/orientador/2